services:
   postgres:
      image: postgres:16
      ports:
        - "5432:5432"
      env_file:
         database.env
   cache:
     image: redis:7.4-alpine
     restart: always
     ports:
       - "6379:6379"
   auth:
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - "50051:50051"
      depends_on:
        - postgres
   cart:
     build:
        context: .
        dockerfile: ./Dockerfile.cart
     ports:
       - "50052:50052"
     depends_on:
       - cache
